### PR TITLE
Adapted Tokens service to Secret Store 1.0.13.Final

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
Please, do not bump Hawkular main with this version. I'll bump it with the related changes there on a new PR.

**Comment by jpkrohling** [comment]
@mtho11 , @ammendonca , @karelhala , would you please review/merge/release ?

**Comment by jpkrohling** [comment]
@vrockai , you are also welcome to review/merge/release :)

**Comment by vrockai** [comment]
@jpkrohling - doesn't this require PRs in consumer repos, too?

**Comment by jpkrohling** [comment]
Yes, hence the need for a release :) Once this is released, I'll update the hawkular PR to point to this new version.

**Comment by jpkrohling** [comment]
https://github.com/hawkular/hawkular/pull/840

**Comment by vrockai** [comment]
:+1: looks good then!

**Pull request merged**
