### PR TITLE
HAWKULAR-565 Bring/expose the new Inventory REST APIs into the ui-services 

### PR DESCRIPTION
**Pull request by jkremser**
This PR exposes the functionality that is new in Inventory `0.3.0`

NOTE: this requires the ui code to change, because some of the resources were renamed

### CODE REVIEW

**Comment by mtho11** [comment]
So this should have a do not merge tag on it?

**Comment by mtho11** [comment]
@Jiri-Kremser do you plan on making those changes needed?

**Comment by jkremser** [comment]
> So this should have a do not merge tag on it?

right, well, it's always kind of chicken-egg problem here, what should go first? The backend change, the ui-services that depends on this backend api? or the hawkular/hawkular ui code that uses the ui-services, but at the same time increases the version of the component with the backend change. 

Obviously the backend change can go first, because it doesn't depend on the UI (nor ui-services), but it's not so clear with the `hawkular/hawkular` and `hawkular/ui-services`, in ideal world the 2 PRs should be merged in the same moment. Or firstly, release the new version of the ui-services and let the hawkular ui still depend on the latest-1 version.

so it can be merged provided the hawkular ui will not depend on it immediately 

> do you plan on making those changes needed?

yes, I can do that (tomorrow perhaps)

@vrockai  could you please review?

**Comment by vrockai** [comment]
@Jiri-Kremser , I just went through the code and it seems fine. Just two tiny remarks:
- Please don't add dist files to the commit. The dist is generated before release and it's part of the release commit.
- Could you please add rest-tests for new entities?

**Comment by jkremser** [comment]
> Please don't add dist files to the commit. The dist is generated before release and it's part of the release commit.
- [x] checked

> Could you please add rest-tests for new entities?
- [x] checked

**Comment by jkremser** [comment]
rebased against latest master and ready to merge (this PR should go right after this one https://github.com/hawkular/hawkular/pull/434)

**Comment by mtho11** [comment]
Merged #28

**Pull request merged**
