### PR TITLE
HAWKULAR-152

### PR DESCRIPTION
**Pull request by stefannegrea**

### CODE REVIEW

**Comment by mtho11** [comment]
This is post M1 merge.

**Comment by vrockai** [comment]
There is a known issue in the PR which needs to be resolved for the rest tests to work. I'm going to look at this.

**Comment by pilhuhn** [comment]
What is the status of this one?

**Comment by vrockai** [comment]
@pilhuhn , please close this PR, this is already resolved.

**Comment by pilhuhn** [comment]
Thanks @vrockai. Was thinking so, but wanted confirmation :)

**Pull request closed without merging**
